# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: LEE EUNBI
title: Unity/Unreal Developers
email: leeub0329@naver.com
# email_title: Email (Email title override)
phone: 010-5274-9498
# phone_title: Phone (Phone title override)
website: https://blog.naver.com/leeub0329
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username: ub0329
instagram_username: eunbi_ya



# Additional icon links
additional_links:
- title: Link name
  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/eunbi.jpg
about_content: | # this will include new lines to allow paragraphs
    ## <mark>운명은 남이 개척하는 것이 아닌, 내가 개척하는 것이다.</mark>
    ## 인적사항
     - 이름: 이은비
     - 나이: 22세
     - 거주지: 남양주시
    ## 학력
     - 마석고등학교 2020 졸업
     - <a href="https://hcms.hallym.ac.kr/info-s/Softwear/ContentsIT/contentsIT.do">정보과학대학 소프트웨학부 콘텐츠it</a> 2020~ ing
    ## 전공
    - 소프트웨어학부 콘텐츠IT
    - 식품영양학    
    ## 취미
    - 보드타기, 게임 분석, 카페 공부, 제과제빵, 책읽기
content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: 공모전
        about_content:# 환경 보호 게임
         
            
          
  - title: Experience
    layout: list
    content:
      - layout: left
        title: <mark>씨애랑</mark>
        sub_title: 소프트웨어 학술 동아리
        caption: 2022~
        
        quote: >
          하계 방학 워크숍 & SW 전시회
       
          
          
       
  - title: Education
    layout: list
    content:
      - layout: top-right
        title: VR/AR 게임 개발자
        sub_title: Unity
        caption: Date Range (eg. 2022)
        quote: >
          유니티 개발에 대한 기본 지식과 개발자의 역량에 대해 배움
        description: | # this will include new lines to allow paragraphs
          사용하는 언어: <mark>C#, java,</mark> 리눅스, C
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      소프트웨어 공부 중 유니티, 언리얼 개발에 더 관심이 많습니다. 게임에 대해 생각하고 구현하는 과정을 즐기며 이행하여 앞으로 더 획기적인 게임 개발을 할 것입니다.
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
